"""MathModel AI — Mock provider for testing.

Used when external API keys are not available.
Always sets is_mock = true on responses.
"""

from __future__ import annotations

import json
import uuid
from typing import Any, AsyncIterator, Optional, Type

from pydantic import BaseModel

from mathmodel.providers.base import (
    BaseModelProvider,
    GenerationRequest,
    GenerationResponse,
    StructuredGenerationRequest,
    UsageInfo,
)


class MockProvider(BaseModelProvider):
    """Mock provider for testing workflows without real API calls.

    Returns deterministic responses. Always marks is_mock = true.
    Only valid for testing: workflow, schema, state, error handling.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        default_model: str = "mock-model",
        fixed_response: Optional[str] = None,
    ):
        super().__init__(api_key=api_key, default_model=default_model)
        self.fixed_response = fixed_response

    @property
    def provider_name(self) -> str:
        return "mock"

    async def generate(self, request: GenerationRequest) -> GenerationResponse:
        model = request.model or self.default_model
        content = self.fixed_response or self._make_response(request.prompt)
        usage = UsageInfo(
            prompt_tokens=len(request.prompt.split()),
            completion_tokens=len(content.split()),
        )
        usage.total_tokens = usage.prompt_tokens + usage.completion_tokens
        self._record_usage(usage)
        return GenerationResponse(
            content=content,
            model=model,
            usage=usage,
            finish_reason="stop",
            is_mock=True,
        )

    async def structured_generate(
        self, request: StructuredGenerationRequest
    ) -> BaseModel:
        """Return a default instance of the requested schema."""
        schema = request.output_schema
        # Try to construct a sensible default instance
        try:
            # Create with default values
            instance = schema()
        except Exception:
            # If that fails, create a minimal dict
            fields = schema.model_fields
            defaults = {}
            for name, field in fields.items():
                if field.default is not None:
                    defaults[name] = field.default
                elif field.annotation == str:
                    defaults[name] = ""
                elif field.annotation == int:
                    defaults[name] = 0
                elif field.annotation == float:
                    defaults[name] = 0.0
                elif field.annotation == bool:
                    defaults[name] = False
                elif field.annotation == list:
                    defaults[name] = []
                elif field.annotation == dict:
                    defaults[name] = {}
                else:
                    defaults[name] = None
            instance = schema(**defaults)
        return instance

    async def stream(self, request: GenerationRequest) -> AsyncIterator[str]:
        """Stream mock response word by word."""
        content = self.fixed_response or self._make_response(request.prompt)
        words = content.split()
        for word in words:
            yield word + " "

    def _make_response(self, prompt: str) -> str:
        """Generate a deterministic mock response."""
        prompt_preview = prompt[:100].replace("\n", " ")
        return (
            f'[MOCK RESPONSE] This is a mock response for prompt: "{prompt_preview}..." '
            f"Mock ID: {uuid.uuid4().hex[:8]}. "
            "This response was generated by MockProvider and is not a real LLM output."
        )